export function cityToCountry(city) {
    const cityMap = {
        'Tokyo': 'japan',
        'Osaka': 'japan',
        'Kyoto': 'japan',
        'Sapporo': 'japan',
        'Fukuoka': 'japan',
        'Beijing': 'china',
        'Shanghai': 'china',
        'Guangzhou': 'china',
        'Shenzhen': 'china',
        'Hangzhou': 'china',
        'Taipei': 'taiwan',
        'Taichung': 'taiwan',
        'Kaohsiung': 'taiwan',
        'Tainan': 'taiwan',
        'Hong Kong': 'hongkong',
        'Manila': 'philippines',
        'Cebu': 'philippines',
        'Boracay': 'philippines',
        'Palawan': 'philippines',
        'Bali': 'indonesia',
        'Jakarta': 'indonesia',
        'Yogyakarta': 'indonesia',
        'Bandung': 'indonesia',
        'Bangkok': 'thailand',
        'Chiang Mai': 'thailand',
        'Phuket': 'thailand',
        'Pattaya': 'thailand',
        'Hanoi': 'vietnam',
        'Ho Chi Minh City': 'vietnam',
        'Da Nang': 'vietnam',
        'Ha Long Bay': 'vietnam',
        'Singapore': 'singapore',
        'Kuala Lumpur': 'malaysia',
        'Johor Bahru': 'malaysia',
        'Penang': 'malaysia',
        'Kota Kinabalu': 'malaysia',
        'New York': 'united states',
        'Los Angeles': 'united states',
        'Las Vegas': 'united states',
        'San Francisco': 'united states',
        'Miami': 'united states',
        'Toronto': 'canada',
        'Vancouver': 'canada',
        'Montreal': 'canada',
        'Quebec City': 'canada',
        'Sydney': 'australia',
        'Melbourne': 'australia',
        'Brisbane': 'australia',
        'Perth': 'australia',
        'London': 'united kingdom',
        'Edinburgh': 'united kingdom',
        'Manchester': 'united kingdom',
        'Liverpool': 'united kingdom',
        'Berlin': 'germany',
        'Munich': 'germany',
        'Frankfurt': 'germany',
        'Hamburg': 'germany',
        'Paris': 'france',
        'Nice': 'france',
        'Lyon': 'france',
        'Marseille': 'france',
        'Rome': 'italy',
        'Venice': 'italy',
        'Florence': 'italy',
        'Milan': 'italy',
        'Madrid': 'spain',
        'Barcelona': 'spain',
        'Seville': 'spain',
        'Valencia': 'spain',
    };
    return cityMap[city] || null;
}

export function countryToKorean(country) {
    const countryMap = {
        'japan': '일본',
        'china': '중국',
        'taiwan': '대만',
        'hongkong': '홍콩',
        'philippines': '필리핀',
        'indonesia': '인도네시아',
        'thailand': '태국',
        'vietnam': '베트남',
        'singapore': '싱가포르',
        'malaysia': '말레이시아',
        'united states': '미국',
        'canada': '캐나다',
        'australia': '호주',
        'united kingdom': '영국',
        'germany': '독일',
        'france': '프랑스',
        'italy': '이탈리아',
        'spain': '스페인'
    };

    return countryMap[country] || '알 수 없는 나라';
}

export function cityToKorean(city) {
    const cityMap = {
        'Tokyo': '도쿄',
        'Osaka': '오사카',
        'Kyoto': '교토',
        'Sapporo': '삿포로',
        'Fukuoka': '후쿠오카',
        'Beijing': '베이징',
        'Shanghai': '상하이',
        'Guangzhou': '광저우',
        'Shenzhen': '선전',
        'Hangzhou': '항저우',
        'Taipei': '타이페이',
        'Taichung': '타이중',
        'Kaohsiung': '가오슝',
        'Tainan': '타이난',
        'Hong Kong': '홍콩',
        'Manila': '마닐라',
        'Cebu': '세부',
        'Boracay': '보라카이',
        'Palawan': '팔라완',
        'Bali': '발리',
        'Jakarta': '자카르타',
        'Yogyakarta': '욕야카르타',
        'Bandung': '반둥',
        'Bangkok': '방콕',
        'Chiang Mai': '치앙마이',
        'Phuket': '푸켓',
        'Pattaya': '파타야',
        'Hanoi': '하노이',
        'Ho Chi Minh City': '호치민시',
        'Da Nang': '다낭',
        'Ha Long Bay': '하롱베이',
        'Singapore': '싱가포르',
        'Kuala Lumpur': '쿠알라룸푸르',
        'Johor Bahru': '조호르바루',
        'Penang': '페낭',
        'Kota Kinabalu': '코타키나발루',
        'New York': '뉴욕',
        'Los Angeles': '로스앤젤레스',
        'Las Vegas': '라스베가스',
        'San Francisco': '샌프란시스코',
        'Miami': '마이애미',
        'Toronto': '토론토',
        'Vancouver': '밴쿠버',
        'Montreal': '몬트리올',
        'Quebec City': '퀘벡',
        'Sydney': '시드니',
        'Melbourne': '멜버른',
        'Brisbane': '브리즈번',
        'Perth': '퍼스',
        'London': '런던',
        'Edinburgh': '에든버러',
        'Manchester': '맨체스터',
        'Liverpool': '리버풀',
        'Berlin': '베를린',
        'Munich': '뮌헨',
        'Frankfurt': '프랑크푸르트',
        'Hamburg': '함부르크',
        'Paris': '파리',
        'Nice': '니스',
        'Lyon': '리옹',
        'Marseille': '마르세유',
        'Rome': '로마',
        'Venice': '베네치아',
        'Florence': '피렌체',
        'Milan': '밀라노',
        'Madrid': '마드리드',
        'Barcelona': '바르셀로나',
        'Seville': '세비야',
        'Valencia': '발렌시아',
    };

    return cityMap[city] || '알 수 없는 도시';
}


export function cityToImageFile(city) {
    const country = cityToCountry(city); // Get the country for the city
    if (!country) return 'unknown_country.png';

    // Dynamically construct the image file name by appending '.png' to the country name
    return `${country}.png`;
}
